# This is a basic workflow to help you get started with Actions

name: CI-dagger-run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - uses: actions/setup-node@v4
      - name: Dagger
        uses: dagger/dagger-for-github@test-dash-m
        with:
          workdir: db-service
          verb: run
          args: node build.js
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.9.3"
